import { useState } from "react";
import { FileDown } from "lucide-react";
import type { Asset, Holding, FxRate } from "@shared/schema";
import type { PortfolioSummary } from "@/lib/portfolio";
import { formatSEK, formatPct } from "@/lib/portfolio";
import { buildAccountSummaries, formatDateForFilename } from "@/lib/pdf-export";

interface ExportPdfButtonProps {
  summary: PortfolioSummary;
  holdings: Holding[];
  assets: Asset[];
  fxRates: FxRate[];
}

export function ExportPdfButton({ summary, holdings, assets, fxRates }: ExportPdfButtonProps) {
  const [isExporting, setIsExporting] = useState(false);

  const generateMarkdown = (): string => {
    const accounts = buildAccountSummaries(holdings, assets, fxRates);
    const date = new Date().toLocaleDateString("sv-SE", { year: "numeric", month: "long", day: "numeric" });

    let md = `# Portfolio Report

Generated: ${date}

---

## Summary

| Metric | Value |
|--------|-------|
| **Total Portfolio Value** | ${formatSEK(summary.totalValueSEK)} |
| **Total Gain/Loss** | ${formatSEK(summary.totalGainSEK)} (${formatPct(summary.totalGainPct)}) |
| **Cost Basis** | ${formatSEK(summary.totalCostSEK)} |
| **Total Dividends** | ${formatSEK(summary.totalDividendsSEK)} |

---

## Account Breakdown

| Account | Value (SEK) | % of Total |
|---------|-------------|------------|
`;

    for (const acc of accounts) {
      const pct = summary.totalValueSEK > 0 ? ((acc.valueSEK / summary.totalValueSEK) * 100).toFixed(1) : "—";
      md += `| ${acc.name} | ${formatSEK(acc.valueSEK)} | ${pct}% |\n`;
    }
    md += `| **Total** | **${formatSEK(summary.totalValueSEK)}** | **100%** |\n\n`;

    md += `---

## Holdings Detail

| Asset | Account | Qty | Price | Value (SEK) | Gain/Loss |
|-------|---------|-----|-------|-------------|-----------|\n`;

    for (const acc of accounts) {
      for (const { asset, holding, valueSEK, gainPct } of acc.holdings) {
        const price = holding.currentPrice ? `${holding.currentPrice.toFixed(2)} ${asset.currency}` : "—";
        md += `| ${asset.name} | ${holding.account} | ${holding.quantity} | ${price} | ${formatSEK(valueSEK)} | ${formatPct(gainPct)} |\n`;
      }
    }

    md += `\n---

*Generated by Portfolio Tracker*
`;

    return md;
  };

  const handleExport = () => {
    if (isExporting) return;

    const markdown = generateMarkdown();
    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = url;
    a.download = `portfolio-report-${formatDateForFilename()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <button
      onClick={handleExport}
      disabled={isExporting}
      className="flex items-center gap-2 px-3 py-2 text-sm font-medium rounded-md bg-secondary text-secondary-foreground hover:bg-secondary/80 transition-colors disabled:opacity-60"
      title="Exportera till Markdown"
    >
      <FileDown size={14} />
      Exportera Markdown
    </button>
  );
}